### ISSUE TITLE
Are the getting started instructions in the contributing guide current? 

### ISSUE THREAD

**Issue by Morganjackson** [muffinjs/cli#27]
The getting started [link](http://muffin.cafe/guide/get-started) in the readme looks like it needs to be updated (404) so I followed the setup instructions in the contributing guide but I cant get past ``npm link``.

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "link"
npm ERR! node v4.2.6
npm ERR! npm  v3.7.1
npm ERR! path /usr/local/lib/node_modules/muffin/dist/bin/index
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/muffin/dist/bin/index'
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/muffin/dist/bin/index'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

Looks like  ``dist`` is missing from ``/usr/local/lib/node_modules/muffin/``

**Comment by leo** [comment]
In its current state, muffin isn't fully stable. Because of this, the site that contains the "Getting started" docs isn't ready either. I will start moving some parts around today and after that I'll adjust the `CONTRIBUTING.md` and let you know. :blush:

But so far, you should me able to make it work by running the `gulp` command within the repository on your local device. This will transpile the source code and put it into `dist`.

**Comment by leo** [comment]
Should work fine now! Please clone all the parts again and let me know if something isn't working correctly. You can find the updated instructions [here](https://github.com/muffinjs/server/blob/master/CONTRIBUTING.md).
